Gyutae
sparta-nullnull/otil pull request #13
Opened 2023-12-07 16:03 UTC by baegyutae

좋아요 생성, 삭제 기능 구현 완료

2023-12-08 09:13 UTC, vanillacake369 requested changes
고생하셨습니다아아~!~!
요청사항에 대해서 이야기 나눠보아요~!~!

2023-12-08 10:11 UTC, baegyutae commented on src/main/java/com/spartanullnull/otil/domain/like/controller/LikeController.java
> +@RequestMapping("/api/posts")
넵! 저건 언제나 어렵네요! 이따 밋업 시간에 집중해서 배우겠습니다!

2023-12-08 10:12 UTC, hoonssss approved these changes

2023-12-08 10:12 UTC, baegyutae commented on src/main/java/com/spartanullnull/otil/domain/like/controller/LikeController.java
> +    public ResponseEntity<String> createLikeForPost(
좋아요를 눌렀을때 문구가 나왔으면 하는 마음에 String을 썼습니다 ㅠ
PostMan에 절여지다보니 그렇게 됐네요 ㅠ

2023-12-08 10:14 UTC, baegyutae commented on src/main/java/com/spartanullnull/otil/domain/like/controller/LikeController.java
> +    public ResponseEntity<String> createLikeForPost(
일단 저의 의도는 한번 봤을 때 어떤 기능인지 확실하게 인지할 수 있도록 쓰자였습니다!
혹시 어떤 식으로 쓰면 좋을까요?

2023-12-08 10:14 UTC, baegyutae commented on src/main/java/com/spartanullnull/otil/domain/like/service/LikeService.java
> +            .orElseThrow(() -> new EntityNotFoundException("사용자를 찾을 수 없습니다."));
네 알겠습니다!

2023-12-08 10:15 UTC, baegyutae commented on src/main/java/com/spartanullnull/otil/domain/like/entity/Like.java
> +    private User user;
아 그건 놓친 부분입니다 ㅠ
게시물에 대한 좋아요! 라는 것만 생각하다보니 놓친 부분입니다!

2023-12-09 07:35 UTC, vanillacake369 requested changes
고생하셨습니다~!
꼭 밋업 채널에서 이야기 나눠보아요!

2023-12-09 07:35 UTC, vanillacake369 commented on src/main/java/com/spartanullnull/otil/domain/comment/service/CommentService.java
>          // 기존 댓글 확인
댓글 update/delete 요청 시, 로그인 사용자가 댓글의 소유주인지 검증하는 로직이 빠져있지 않나 싶습니다!
제가 잘 몰라서 그러는데 혹시 확인 해주실 수 있으실까요??

2023-12-09 07:35 UTC, vanillacake369 commented on src/main/java/com/spartanullnull/otil/domain/comment/service/CommentService.java
>          // 댓글 삭제
댓글 삭제 또한 마찬가지입니다!

> 댓글 update/delete 요청 시, 로그인 사용자가 댓글의 소유주인지 검증하는 로직이 빠져있지 않나 싶습니다!
> 제가 잘 몰라서 그러는데 혹시 확인 해주실 수 있으실까요??

2023-12-09 07:35 UTC, vanillacake369 commented on src/main/java/com/spartanullnull/otil/domain/like/controller/CommentLikeController.java
> +        commentLikeService.createLikeForComment(userDetails.getUser().getId(), commentId);
좋아요 API 에 대해서 비회원이 요청한 경우, 예외 발생하는 검증 로직이 빠져있지 않나 싶은데요~!
혹시 규태님은 이 부분에 대해서 어떻게 생각하시나요??

2023-12-09 07:35 UTC, vanillacake369 commented on src/main/java/com/spartanullnull/otil/domain/like/entity/Like.java
>      private Comment comment;
like로 post와 record를 처리하게 되는 경우, 아래와 같은 문제가 발생한다고 생각합니다!
- post,comment 둘 중 하나 좋아요 선택 시, 하나만 연관관계 형성됨
	- 불필요한 PK값을 가지게 되지 않나 싶음
	- 이를 위해 recommend로 like와 분리하여 생성하지 않았었나 싶네용!
규태님의 생각이 궁금해요!

2023-12-09 07:35 UTC, vanillacake369 commented on src/main/java/com/spartanullnull/otil/domain/like/repository/LikeRepository.java
> +    List<Object[]> findTop3PostsByLikes(Pageable pageable);
Pageable은 어떤 클래스일까요?? 제가 아직 JPQL은 몰라서요 😅

2023-12-09 07:57 UTC, baegyutae commented on src/main/java/com/spartanullnull/otil/domain/like/repository/LikeRepository.java
> +    List<Object[]> findTop3PostsByLikes(Pageable pageable);
제가 Top3를 어떻게 하면 좋을까 찾아보다가 JPQL Pageable을 봤는데요
JPQL을 이용하면 엔티티에 대한 쿼리를 SQL과 별도로 작성할 수 있고 DB에 독립적인 방법으로 쿼리를 작성할 수 있다고 합니다.
그리고 Pageable은 Spring Data에서 제공하는 인터페이스고 페이징 및 정렬 정보를 전달할 수 있다고 합니다.
결국 제가 사용한 핵심 기능은 Pageable 인터페이스에서 페이징입니다! service단에서 pagesize 요구값을 3을 넣어줘서 3개만 보이게끔 해주었어요!
뭔가 설명이 어설프네요

2023-12-09 07:58 UTC, vanillacake369 commented on src/main/java/com/spartanullnull/otil/domain/like/repository/LikeRepository.java
> +    List<Object[]> findTop3PostsByLikes(Pageable pageable);
아핫!! 그렇군요!! 이렇게 배우고 가네요오 ㅎㅅㅎ 정말 감사합니다!!!!!

2023-12-09 08:01 UTC, baegyutae commented on src/main/java/com/spartanullnull/otil/domain/like/controller/CommentLikeController.java
> +        commentLikeService.createLikeForComment(userDetails.getUser().getId(), commentId);
아 이런걸 매번 놓치네요 수정해서 다시 커밋하겠습니다!

2023-12-09 08:19 UTC, baegyutae commented on src/main/java/com/spartanullnull/otil/domain/comment/service/CommentService.java
>          // 기존 댓글 확인
넵! 수정완료했습니다!

2023-12-09 08:19 UTC, baegyutae commented on src/main/java/com/spartanullnull/otil/domain/comment/service/CommentService.java
>          // 댓글 삭제
넵! 수정완료했습니다!

2023-12-09 13:11 UTC, vanillacake369 approved these changes

2023-12-09 13:14 UTC, merged