User , Reportpost 구현
sparta-nullnull/otil pull request #14
Opened 2023-12-09 09:46 UTC by hoonssss

2023-12-09 14:33 UTC, vanillacake369 requested changes

2023-12-09 14:33 UTC, vanillacake369 commented on src/main/java/com/spartanullnull/otil/domain/reportpost/controller/ReportPostController.java
> +        String password = requestDto.getPassword();
어드민 권한만 있는 사용자가 접근할 수 있게끔 하는 건 어떨까용ㅇ??

2023-12-09 14:33 UTC, vanillacake369 commented on src/main/java/com/spartanullnull/otil/domain/reportpost/controller/ReportPostController.java
> +            String password = requestDto.getPassword();
어드민 권한만 있는 사용자가 접근할 수 있게끔 하는 건 어떨까용ㅇ?? 222222

2023-12-09 14:33 UTC, vanillacake369 commented on src/main/java/com/spartanullnull/otil/domain/reportpost/service/ReportPostService.java
> +
`@Transactional`을 추가해야 더티체킹에 따라 값이 변경처리 하는걸로 알고 있는데요~!
혹시 확인 해주실 수 있나요오오?~?

2023-12-10 09:51 UTC, hoonssss commented on src/main/java/com/spartanullnull/otil/domain/reportpost/controller/ReportPostController.java
> +        String password = requestDto.getPassword();
수정 완료하였습니다!

2023-12-10 10:19 UTC, baegyutae approved these changes
수고하셨습니다!

2023-12-10 16:06 UTC, merged