refactor:게시글생성(유저버전) & feat:게시글수정(유저x),삭제(유저x)
sparta-nullnull/otil pull request #8
Opened 2023-12-07 08:36 UTC by kimhanshin4

- 게시글 생성(createPost) 유저버전으로 수정하였습니다.
- 게시글 수정, 삭제를 추가하였는데 아직 둘다 유저버전은 아닙니다.
- 도메인 안에 따로 넣어져 있던 domain/common/util/BaseTime은 삭제하였습니다 => otil/util/BaseTime 사용

2023-12-07 12:11 UTC, hoonssss approved these changes

2023-12-07 14:42 UTC, vanillacake369 requested changes
고생하셨습니다!
요청 드린 부분 관련해서 같이 이야기 나눠보아요오~!~!

2023-12-07 14:42 UTC, vanillacake369 commented on src/main/java/com/spartanullnull/otil/domain/post/controller/PostController.java
> +        }
try-catch 쓰시는 건 배울 점이구 너무나도 좋습니다! (왜 저는 프로덕션에 try-catch를 안 넣었을까요,,,)
해당 catch에서 IllegalArgumentException으로 처리하시는데, 코드 의도가 도메인 예외처리를 하기위함이라고 추측되는데요~

저는 아래와 같이 생각해서 코드 수정을 요청드리오는데 혹시 한신님 생각은 어떠실지 궁금하네요!!

1. 혹시 도메인 예외처리를 하기 위함이시라면, global exception handler가 처리할 수 있게 하는 게 좋지 않을까 생각됩니다!
2. 도메인 예외처리가 아닌 예외에 대해서는 try-catch를 사용하여 예기치 못 한 exception은 컨트롤러 단에서 해결할 수 있게끔 하는 게 좋다고 생각합니다!

2023-12-07 14:42 UTC, vanillacake369 commented on src/main/java/com/spartanullnull/otil/domain/post/controller/PostController.java
> +    }
해당 부분은 delete에 대해 void 를 반환하게끔 해주셨는데요~!
혹시 delete 성공했는지, 실패했는지 api 호출단에서 확인하려면 어떻게 해주어야할까요??
이 부분은 규태님이랑도 이야기 나눠보고 싶어요!
@baegyutae

2023-12-07 14:42 UTC, vanillacake369 commented on src/main/java/com/spartanullnull/otil/domain/post/service/PostService.java
> +    private void findByUsername(Post post, String accountId) {
함수명에 코드 의도가 잘 드러나지 않아서 아쉬운 것 같아요,,!!
로그인한 사용자가 Post의 소유자인지에 대한 역할수행을 findByUserName로 규정짓기는 어색하다고 느낍니다!!
같이 이야기 해볼 수 있으면 좋겠습니다!

클린코드 :: 의미 있는 이름 관련해서 첨부해보아요~
https://ittrue.tistory.com/336

2023-12-07 14:42 UTC, vanillacake369 commented on src/main/java/com/spartanullnull/otil/domain/post/service/PostService.java
> +    }
상관은 없지만 code clutter가 존재하는 것 같아 리뷰 남깁니다!
delete는 내부적으로 `@Transactional`이 붙어 있습니다.
따라서 method level `@Transactional`을 붙여줄 필요가 있을까 싶습니다,,!

delete 관련해서 아래 링크를 첨부해보아요~
https://velog.io/@moonyoung/JPA-JPA-Repository-%EC%88%98%EC%A0%95%EC%82%AD%EC%A0%9C%EC%99%80-%ED%8A%B8%EB%9E%9C%EC%9E%AD%EC%85%98

2023-12-07 14:42 UTC, vanillacake369 commented on src/main/java/com/spartanullnull/otil/domain/post/entity/Post.java
> +
저는 생성자에 대해서 사용하지 않는다면 최대한 만들지 않거나, 만들게 되더라도 최소한으로 만들거나 의도를 담아야한다고 생각을 하는데요!

물론 지금은 비즈니스가 복잡하지 않고 도메인의 범위가 크지 않아서 간단한데,
엔티티가 커지게 되고 여러 팀원이 엔티티를 가져가서 쓸 때, 의도치 않은 데이터에 대해 객체 생성이 가능하다고 생각하거든요.
(제가 NoArgs를 PROTECTED로 access limit 둔 것과 마찬가지로요!!)


혹시 한신님의 생각은 어떠신지 궁금해요!

2023-12-07 14:42 UTC, vanillacake369 commented on src/main/java/com/spartanullnull/otil/domain/post/controller/PostController.java
> +    public ResponseEntity<CommonResponseDto> modifyPost(@PathVariable Long postId,
어떤 부분은 CommonResponseDto로, 어떤 부분은 PostResponseDto로 반환하고 있어서 
API 레벨에서 바라봤을 때 조금 통일성이 떨어지는 것 같아요 

혹시 한신님의 생각은 어떠신가요?

2023-12-07 14:42 UTC, vanillacake369 commented on src/main/java/com/spartanullnull/otil/domain/post/controller/PostController.java
>          return ResponseEntity.status(201).body(responseDto);
201로 처리하신 부분이 인상깊네요!! 🙌👏

2023-12-08 01:50 UTC, baegyutae approved these changes

2023-12-08 01:50 UTC, baegyutae commented on src/main/java/com/spartanullnull/otil/domain/post/controller/PostController.java
>          return ResponseEntity.status(201).body(responseDto);
오호 저도 배워야겠습니당

2023-12-08 01:50 UTC, baegyutae commented on src/main/java/com/spartanullnull/otil/domain/post/controller/PostController.java
> +    public ResponseEntity<CommonResponseDto> modifyPost(@PathVariable Long postId,
저도 같은 생각입니다!

2023-12-08 01:50 UTC, baegyutae commented on src/main/java/com/spartanullnull/otil/domain/post/controller/PostController.java
> +    }
앗 저도 지훈님 댓글보고 찾아보고 생각을 해봤는데요!
boolean을 써서 삭제 작업 성공여부를 판단후에
if else 구문을 써서 작업이 성공하면 HttpStatus.NO_CONTENT를 반환하고
실패하면 HttpStatus.NOT_FOUND를 써주면 되지않을까 싶은데
이러면 너무 코드가 길어질까요?

2023-12-08 01:50 UTC, baegyutae commented on src/main/java/com/spartanullnull/otil/domain/post/entity/Post.java
> +
저도 같은 피드백을 받았습니다! 확실히 프로젝트 단위가 커지면 커질수록
엔티티는 깔끔해야 한다고 생각합니다!

2023-12-09 07:42 UTC, merged